name: TDD CI Pipeline

on:                   # specifies actions that trigger the workflow
  push:               # runs on pushing to branches specified
    branches: [main]
  pull_request:       # runs on pull request to branches specified
    branches: [main]

jobs:
  test:
    runs-on: macos-latest             # specifies OS of virtual machine on github's server that workflow will run on
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3     # clones code onto vm - important else no access to code

      - name: Set up JDK 17
        uses: actions/setup-java@v3   # installs java with version and distribution specified below
        with:
          java-version: '17'
          distribution: 'temurin'     # good for general use and is default and recommended. possible: corretto, microsoft, zulu, graalvm, oracle, semeru

      - name: Build and Run Tests
        run: mvn clean install test   # specifies command to run
